name: CI/CD Pipeline

on:
  push:

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: npm install
      - uses: actions/upload-artifact@v4
        with:
          name: node_modules
          path: ./node_modules
  test:
    needs: install
    strategy:
      matrix:
        maxWorkers: [1, 2, 3, 4]
    name: Tests (${{ matrix.maxWorkers }} Core(s))
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: node_modules
          path: ./node_modules
      - name: Run tests
        run: npm jest --silent --maxWorkers=${{ matrix.maxWorkers }}
