name: CI/CD Pipeline

on:
  push:

jobs:
  test:
    strategy:
      matrix:
        #   runner:
        #     - blacksmith-2vcpu-ubuntu-2204
        #     - blacksmith-4vcpu-ubuntu-2204
        #     - blacksmith-8vcpu-ubuntu-2204
        #     - blacksmith-16vcpu-ubuntu-2204
        maxWorkers: [1, 2, 3, 4]
    name: Tests (${{ matrix.maxWorkers }} Core(s))
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: npm jest --silent --maxWorkers=${{ matrix.maxWorkers }}
